spring:
  application:
    name: PAYMENT-SERVICE

  h2:
    console:
      enabled: true

server:
  port: 9191

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka