spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

server:
  port: 8989
  
  eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        default-zone: http://localhost:8761/eureka